domino14/Webolith

djAerolith/requirements.txt, djAerolith/settings.py, djAerolith/wordwalls/management/commands/backup.py
Make script for AWS S3 backups.
=> Script for S3 backups.

djAerolith/lib/response.py, djAerolith/wordwalls/game.py, djAerolith/wordwalls/static/js/wordwalls/views/AppView.js, djAerolith/wordwalls/views.py
- Detect game over condition on backend and send error message.
- Properly display error message on front end.
=> Fixed repeated solutions bug.

Dockerfile, dc-prod.yml, djAerolith/requirements.txt, djAerolith/settings.py, docker-compose.yml
What: Set the postgres DB as the default
Why: cause
close #61
=> Post-migration, set postgres db as the default

djAerolith/flashcards/static/js/flashcards/templates/new_quiz.html, djAerolith/flashcards/views.py
=> Update lexica, remove OWL2 and add CSW15.

djAerolith/base/urls.py, djAerolith/base/views.py, djAerolith/flashcards/static/js/flashcards/main.js, djAerolith/flashcards/static/js/flashcards/views/app.js, djAerolith/flashcards/static/js/flashcards/views/word_lookup.js, djAerolith/flashcards/templates/flashcards/index.html, djAerolith/lib/macondo_interface.py
=> Added simple lookup word functionality for cards.

djAerolith/wordwalls/templates/wordwalls/stats.html
This was broken due to a horrible "feature" in iOS Safari.
http://stackoverflow.com/questions/5515659/javascript-variable-corresponds-to-dom-element-with-the-same-id
=> Change variable names

djAerolith/urls.py, djAerolith/views.py, djAerolith/wordwalls/static/js/wordwalls/error.js, djAerolith/wordwalls/static/js/wordwalls/main.js
=> Add Javascript error logging.

djAerolith/views.py, djAerolith/wordwalls/static/js/wordwalls/error.js, djAerolith/wordwalls/static/js/wordwalls/views/AppView.js, djAerolith/wordwalls/static/js/wordwalls/wordwalls_tests.js
- Does not properly log JSON body. Should probably use an actual mailgun email command rather than `logger.error`
- Queue retries happen for every error. We should only have one active `setTimeout` at any one time.
=> [WIP] Chore/173/error logging guesses emails

djAerolith/base/forms.py, djAerolith/base/locale/es/LC_MESSAGES/django.po, djAerolith/wordwalls/game.py, djAerolith/wordwalls/locale/es/LC_MESSAGES/django.po, djAerolith/wordwalls/static/js/wordwalls/tableCreate.js, djAerolith/wordwalls/templates/wordwalls/index.html, djAerolith/wordwalls/views.py
=> Allow quizzing more/less than 50 words at a time.

djAerolith/wordwalls/tests/test_file_upload.py
=> Reset sequences to avoid failing tests.

circle.yml, djAerolith/settings.py, djAerolith/wordwalls/challenges.py, djAerolith/wordwalls/tests/test_game_logic.py, djAerolith/wordwalls/views.py
Add some needed env vars and parsing logic.
Tests require dictionary dbs.
Add these to S3 and make them available for download. This will only cost me a handful of cents a month or something...
Don't load models at the module level. This breaks tests.
close #179.
=> CircleCI integration.

djAerolith/flashcards/static/js/flashcards/views/word_lookup.js, djAerolith/flashcards/templates/flashcards/index.html
=> Fix word lookup bug.

djAerolith/accounts/models.py, djAerolith/accounts/views.py, djAerolith/wordwalls/management/commands/awardChallengeMedals.py, djAerolith/wordwalls/management/commands/migrate_medals.py, djAerolith/wordwalls/migrations/0010_auto_20170301_0923.py, djAerolith/wordwalls/migrations/0010_medal.py, djAerolith/wordwalls/models.py, djAerolith/wordwalls/stats.py, djAerolith/wordwalls/templates/wordwalls/leaderboard.html, djAerolith/wordwalls/views.py, webpack.config.babel.js
What: Moves to using a Medal model, instead of putting medal data in JSON dumps 
Why: Easier aggregation and faster querying
=> Fix medals

circle.yml
`docker push` webolith:latest -- in order for the cron job to work.
=> Push the “latest” image too.

djAerolith/lib/word_db_helper.py, djAerolith/wordwalls/api.py, djAerolith/wordwalls/management/commands/genNamedLists.py, djAerolith/wordwalls/tests/test_api.py, djAerolith/wordwalls/tests/test_game_logic.py
What: Use a chunk size of 999
Close #234
=> Get SQLite queries in chunks.

djAerolith/wordwalls/management/commands/awardChallengeMedals.py, djAerolith/wordwalls/models.py
=> Add more logging and dry-run.

djAerolith/djaerolith/settings.py, djAerolith/leitner/README.md, djAerolith/registration_app/forms.py, djAerolith/wordwalls/static/js/wordwalls/test/presence.test.js
=> enable recaptcha v2

djAerolith/whitleyCards/views.py
fix an issue from the Django 2.0 upgrade
=> decode encoded search

djAerolith/templates/base.html
See: https://getbootstrap.com/docs/3.3/getting-started/#download-cdn
=> Include js from bootstrap, fixes #427

frontend/eslint.config.js
Tested locally to confirm this confirm works
=> Exhaustive deps lint rule should error

djAerolith/wordwalls/api.py
Link: https://app.codecomet.io/org/5Rp9Qnk4KX3jEPBQJJTBIa/project/M3TD4a7fJS67OAM8faZU1/issue/6wn4zIXmHNKiDo5UAA4Bcu
Summary of issue:
TypeError due to None value for 'desiredTime'.
=> Fix for TypeError due to None value for 'desiredTime'.

djAerolith/wordwalls/api.py
=> Revert "Fix for TypeError due to None value for 'desiredTime'."

frontend/src/flashcard.tsx
The build was fixed but:
- Tiles were rendering as the wrong size
- Need to not have exhaustive deps for the `useEffect`, code comment explains why
=> [wordvault] Final JS fixes

frontend/src/flashcard.tsx
Closes https://github.com/domino14/Webolith/issues/500
=> Allow touch events on flashcard

frontend/src/fsrs_cards.tsx
Closes https://github.com/domino14/Webolith/issues/505
Closes https://github.com/domino14/Webolith/issues/503
=> UX improvements for next card load

frontend/package-lock.json, frontend/src/app_context.tsx, frontend/src/flashcard.tsx, frontend/src/leaderboard.tsx, frontend/src/settings.tsx, frontend/src/timezones.ts
=> new tile colors, stats tweaks, timezone fixes

.cursor/rules/architecture.mdc, .cursor/rules/development.mdc, CLAUDE.md
Mostly porting the rules from word-db-server explaining the high level data models. Also largely for the WordVault frontend since I'm not familiar with the Django/aerolith side of things
=> Add CLAUDE.md and .cursor/rules
